# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/example.proto',
  package='example_service',
  syntax='proto3',
  serialized_pb=_b('\n\x16protocol/example.proto\x12\x0f\x65xample_service\"\"\n\x0e\x43omputeRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"!\n\x0f\x43omputeResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2`\n\x0e\x45xampleService\x12N\n\x07\x43ompute\x12\x1f.example_service.ComputeRequest\x1a .example_service.ComputeResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='example_service.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='example_service.ComputeRequest.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=77,
)


_COMPUTERESPONSE = _descriptor.Descriptor(
  name='ComputeResponse',
  full_name='example_service.ComputeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='example_service.ComputeResponse.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ComputeResponse'] = _COMPUTERESPONSE

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTEREQUEST,
  __module__ = 'protocol.example_pb2'
  # @@protoc_insertion_point(class_scope:example_service.ComputeRequest)
  ))
_sym_db.RegisterMessage(ComputeRequest)

ComputeResponse = _reflection.GeneratedProtocolMessageType('ComputeResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTERESPONSE,
  __module__ = 'protocol.example_pb2'
  # @@protoc_insertion_point(class_scope:example_service.ComputeResponse)
  ))
_sym_db.RegisterMessage(ComputeResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class ExampleServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Compute = channel.unary_unary(
          '/example_service.ExampleService/Compute',
          request_serializer=ComputeRequest.SerializeToString,
          response_deserializer=ComputeResponse.FromString,
          )


  class ExampleServiceServicer(object):

    def Compute(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ExampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Compute': grpc.unary_unary_rpc_method_handler(
            servicer.Compute,
            request_deserializer=ComputeRequest.FromString,
            response_serializer=ComputeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'example_service.ExampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaExampleServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Compute(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaExampleServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Compute(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Compute.future = None


  def beta_create_ExampleService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('example_service.ExampleService', 'Compute'): ComputeRequest.FromString,
    }
    response_serializers = {
      ('example_service.ExampleService', 'Compute'): ComputeResponse.SerializeToString,
    }
    method_implementations = {
      ('example_service.ExampleService', 'Compute'): face_utilities.unary_unary_inline(servicer.Compute),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ExampleService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('example_service.ExampleService', 'Compute'): ComputeRequest.SerializeToString,
    }
    response_deserializers = {
      ('example_service.ExampleService', 'Compute'): ComputeResponse.FromString,
    }
    cardinalities = {
      'Compute': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'example_service.ExampleService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
